Completed Binary Search-2 - Please Review
super30admin/Binary-Search-2 pull request #1292
Opened 2022-09-11 23:38 UTC by sh-ruchi

2022-09-15 17:28 UTC, daredevilteja requested changes

2022-09-15 17:28 UTC, daredevilteja commented on FirstLastPos.java
> +// Time Complexity : 2 O(LOG N)
what is n?

2022-09-15 17:28 UTC, daredevilteja commented on MinElementInRotatedArray.java
> +// Time Complexity : O(Log n)
what is n

2022-09-15 17:28 UTC, daredevilteja commented on SearchInSorterArrUnknownSize.java
> +// Time Compexity : O(log n)
what is n?

2022-09-15 17:29 UTC, daredevilteja commented
Please mention whether it ran successfully on leetcode or not, for every problem.

2022-09-15 22:51 UTC, sharma-ruchika commented on SearchInSorterArrUnknownSize.java
> +// Time Compexity : O(log n)
n is the length of nums array .

2022-09-15 22:52 UTC, sharma-ruchika commented
Its mentioned at the top  line 3 , that it ran successfully on Leetcode.

2022-09-15 22:54 UTC, sharma-ruchika commented on FirstLastPos.java
> +// Time Complexity : 2 O(LOG N)
n is length of array

2022-09-18 12:55 UTC, daredevilteja commented
> Its mentioned at the top line 3 , that it ran successfully on Leetcode.

You mentioned it only for one problem, you have to mention it for all the problems

2022-10-19 01:43 UTC, closed without merging